dist: xenial
language: node_js
node_js:
  - "10.2"
sudo: enabled
before_install:
  - apt-get update
  - apt-get install nasm
install:
  - npm install --global gatsby-cli
  - npm install
  - npm run fetch_data
script:
  - gatsby build